# Default configuration for riscv-softmmu
#
include pci.mak
include usb.mak

CONFIG_SERIAL=y
CONFIG_VIRTIO=y

CONFIG_PFLASH_CFI01=y
CONFIG_ACPI=y
CONFIG_I2C=y
CONFIG_FW_CFG_DMA=y
CONFIG_PCIE_PORT=y
CONFIG_XIO3130=y
CONFIG_IOH3420=y
CONFIG_I82801B11=y
CONFIG_SMBIOS=y
CONFIG_PCI_GENERIC=y
